language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g npm@6.4.1
  - npm install -g jest@24.8.0
script:
  # Run test script
  - npm run test-ci
  # Run linting
#  - npm run lint TODO