language: node_js
cache:
  directories:
    - node_modules
script:
  # Run test script
  - npm run test
  # Run linting
#  - npm run lint TODO
# after_script:
#  - |
#    # Upload coverage to coveralls
#    npm install --save-dev coveralls@2.12.0
#    coveralls < ./coverage/lcov.info